### ISSUE TITLE
/login not found

### ISSUE THREAD

**Issue by sero-dev** [passport/todos-express-auth0#1]
I'm not sure if I missed a step here, but when I run the app and click on the "Sign In" button. I get a 404 for the login in page. Checked the index router, it does not seem to have a route for /login.

Edit: Actually it looks like this is still a WIP. Realized that it was only created 19 days ago.

**Comment by jaredhanson** [comment]
The login route is defined [here](https://github.com/passport/todos-express-auth0/blob/main/routes/auth.js#L36) in `routes/auth.js`.  It's covered in the tutorial in the [add routes](https://www.passportjs.org/tutorials/auth0/routes/) section.
