### ISSUE TITLE
Too many redirects

### ISSUE THREAD

**Issue by hitesh-kulkarni** [passport/todos-express-auth0#2]
https://github.com/passport/todos-express-auth0/blob/30014822da2971808391a4c8d53e578759b7680c/routes/auth.js#L37

Wouldn't this cause too many redirects issue?
Once openid provider authenticates and redirects to callback - we are calling authenticate again - going into endless loop.

Or am I missing something?

**Comment by jaredhanson** [comment]
Have you tried it?

The call to `authenticate()` on the `/oauth2/redirect` route looks for a OAuth 2.0/OpenID response, validates it, and does not redirect to the IDP.  Therefore, there is no redirect loop.

**Comment by hitesh-kulkarni** [comment]
Yes - I tried it - this is what I get 

```
> todos-express-auth0@0.0.0 start C:\oauth-passport\todos-express-auth0
> node ./bin/www

GET / 304 11.486 ms - -
GET /css/base.css 304 1.928 ms - -
GET /css/index.css 304 1.714 ms - -
GET /css/home.css 304 0.610 ms - -
GET /login 302 2.302 ms - 0
GET /oauth2/callback/?state=<state>&code=<code> 302 485.218 ms - 56
GET /login 302 3.659 ms - 0
```

and it continues to go like this until the browser ends up ERR_TOO_MANY_REDIRECTS

**Comment by jaredhanson** [comment]
It looks like the request is going to `/oauth2/callback/` rather than `/oauth2/redirect`, which is where the example is configured.  Have you made modifications to the configuration?

**Comment by hitesh-kulkarni** [comment]
> It looks like the request is going to `/oauth2/callback/` rather than `/oauth2/redirect`, which is where the example is configured. Have you made modifications to the configuration?

Yes - this is how the object is initiated - I checked and all env variables are right as well.

```
passport.use(new OpenIDConnectStrategy({
  issuer: 'https://' + process.env['AUTH0_DOMAIN'] + '/',
  authorizationURL: 'https://' + process.env['AUTH0_DOMAIN'] + '/authorize',
  tokenURL: 'https://' + process.env['AUTH0_DOMAIN'] + '/token',
  userInfoURL: 'https://' + process.env['AUTH0_DOMAIN'] + '/userinfo',
  clientID: process.env['AUTH0_CLIENT_ID'],
  clientSecret: process.env['AUTH0_CLIENT_SECRET'],
  callbackURL: '/oauth2/callback/',
  scope: [ 'profile' ]
}, function verify(issuer, profile, cb) {
  return cb(null, profile);
}));
```
Also tried multiple combinations for this route

```
router.get('/oauth2/callback/*', () => {
  passport.authenticate('openidconnect', {
    successReturnToOrRedirect: '/',
    failureRedirect: '/login'
  });
  console.log(passport);
});

==============

router.get('/oauth2/callback/', () => {
  passport.authenticate('openidconnect', {
    successReturnToOrRedirect: '/',
    failureRedirect: '/login'
  });
  console.log(passport);
});

=================

router.get('/oauth2/callback/', passport.authenticate('openidconnect', {
    successReturnToOrRedirect: '/',
    failureRedirect: '/login'
}));

=================

router.get('/oauth2/callback/*', passport.authenticate('openidconnect', {
    successReturnToOrRedirect: '/',
    failureRedirect: '/login'
}));


```
All of them end up with redirects.
